version: '3.7'
services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - django_static:/home/app/static
      - ./app/gunicorn.conf.py:/home/app/gunicorn.conf.py:ro
    command: >
      bash -c "
       python manage.py collectstatic --noinput &&
       python manage.py compilemessages -l en -l ru
       python manage.py migrate &&
       python -m gunicorn config.wsgi
       "
    expose:
      - "8000"
    depends_on:
      - db
  nginx:
    container_name: nginx
    image: nginx:1.21.6
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - django_static:/www/static:ro
    ports:
      - 80:80
    depends_on:
      - django
  db:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - ${DB_PORT}
volumes:
  django_static:
